# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CurrencyDetails
# Logging
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    com.kaluzny: DEBUG
    org.springframework: INFO
    org.mongodb: DEBUG
# Server configuration
server:
  port: 8082
  sessionTimeout: 30
# Security configuration
security:
  user:
    name: user
    password: user
